from django.core.management.base import BaseCommand

from employees.models import Attendance, Employee

EMPLOYEES = [
    dict(
        name="Aditi Sharma",
        role="Frontend Developer",
        department="Engineering",
        email="aditi.sharma@company.com",
        phone="+91-9876543210",
        image="https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&h=300&fit=crop&crop=faces",
        is_active=True,
        status="Active",
        salary=75000,
        joining_date="2022-03-15",
        location="Bangalore",
        years_of_experience=4.5,
        performance_rating=4.2,
        grade="A",
        last_appraisal_date="2026-01-15",
        last_increment_percent=8,
        attendance=dict(total_working_days=22, days_present=20, days_absent=2, total_leaves=12, leaves_taken=2, leaves_remaining=10),
    ),
    dict(
        name="Rahul Verma",
        role="Backend Developer",
        department="Engineering",
        email="rahul.verma@company.com",
        phone="+91-9876543211",
        image="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop&crop=faces",
        is_active=True,
        status="Active",
        salary=82000,
        joining_date="2021-07-01",
        location="Chennai",
        years_of_experience=5.2,
        performance_rating=4.7,
        grade="A+",
        last_appraisal_date="2026-02-01",
        last_increment_percent=10,
        attendance=dict(total_working_days=22, days_present=22, days_absent=0, total_leaves=12, leaves_taken=0, leaves_remaining=12),
    ),
    dict(
        name="Sneha Iyer",
        role="UI/UX Designer",
        department="Design",
        email="sneha.iyer@company.com",
        phone="+91-9876543212",
        image="https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&h=300&fit=crop&crop=faces",
        is_active=False,
        status="On Leave",
        salary=68000,
        joining_date="2023-01-10",
        location="Mumbai",
        years_of_experience=3.5,
        performance_rating=3.5,
        grade="B",
        last_appraisal_date="2025-12-10",
        last_increment_percent=5,
        attendance=dict(total_working_days=22, days_present=14, days_absent=8, total_leaves=12, leaves_taken=8, leaves_remaining=4),
    ),
    dict(
        name="Vikram Nair",
        role="Project Manager",
        department="Operations",
        email="vikram.nair@company.com",
        phone="+91-9876543213",
        image="https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&h=300&fit=crop&crop=faces",
        is_active=True,
        status="Active",
        salary=95000,
        joining_date="2020-11-20",
        location="Hyderabad",
        years_of_experience=5.8,
        performance_rating=4.9,
        grade="A+",
        last_appraisal_date="2026-01-20",
        last_increment_percent=12,
        attendance=dict(total_working_days=22, days_present=21, days_absent=1, total_leaves=12, leaves_taken=1, leaves_remaining=11),
    ),
    dict(
        name="Priya Menon",
        role="QA Engineer",
        department="Engineering",
        email="priya.menon@company.com",
        phone="+91-9876543214",
        image="https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=300&h=300&fit=crop&crop=faces",
        is_active=False,
        status="Inactive",
        salary=70000,
        joining_date="2022-09-05",
        location="Pune",
        years_of_experience=4,
        performance_rating=3.0,
        grade="C",
        last_appraisal_date="2025-09-05",
        last_increment_percent=0,
        attendance=dict(total_working_days=22, days_present=10, days_absent=12, total_leaves=12, leaves_taken=12, leaves_remaining=0),
    ),
    dict(
        name="Karan Malhotra",
        role="Marketing Manager",
        department="Marketing",
        email="karan.malhotra@company.com",
        phone="+91-9876543215",
        image="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop&crop=faces",
        is_active=True,
        status="Active",
        salary=78000,
        joining_date="2021-04-12",
        location="Delhi",
        years_of_experience=6.0,
        performance_rating=4.3,
        grade="A",
        last_appraisal_date="2026-01-10",
        last_increment_percent=7,
        attendance=dict(total_working_days=22, days_present=21, days_absent=1, total_leaves=12, leaves_taken=1, leaves_remaining=11),
    ),
    dict(
        name="Ananya Reddy",
        role="Content Strategist",
        department="Marketing",
        email="ananya.reddy@company.com",
        phone="+91-9876543216",
        image="https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&h=300&fit=crop&crop=faces",
        is_active=True,
        status="Active",
        salary=62000,
        joining_date="2023-05-22",
        location="Bangalore",
        years_of_experience=2.8,
        performance_rating=4.0,
        grade="B",
        last_appraisal_date="2025-11-22",
        last_increment_percent=6,
        attendance=dict(total_working_days=22, days_present=19, days_absent=3, total_leaves=12, leaves_taken=3, leaves_remaining=9),
    ),
    dict(
        name="Arjun Kapoor",
        role="Sales Executive",
        department="Sales",
        email="arjun.kapoor@company.com",
        phone="+91-9876543217",
        image="https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=300&h=300&fit=crop&crop=faces",
        is_active=True,
        status="Active",
        salary=58000,
        joining_date="2022-08-01",
        location="Mumbai",
        years_of_experience=3.2,
        performance_rating=3.8,
        grade="B",
        last_appraisal_date="2025-10-01",
        last_increment_percent=5,
        attendance=dict(total_working_days=22, days_present=20, days_absent=2, total_leaves=12, leaves_taken=2, leaves_remaining=10),
    ),
    dict(
        name="Divya Krishnan",
        role="Sales Manager",
        department="Sales",
        email="divya.krishnan@company.com",
        phone="+91-9876543218",
        image="https://images.unsplash.com/photo-1544717305-2782549b5136?w=300&h=300&fit=crop&crop=faces",
        is_active=True,
        status="Active",
        salary=89000,
        joining_date="2020-02-17",
        location="Chennai",
        years_of_experience=7.1,
        performance_rating=4.6,
        grade="A+",
        last_appraisal_date="2026-02-17",
        last_increment_percent=9,
        attendance=dict(total_working_days=22, days_present=22, days_absent=0, total_leaves=12, leaves_taken=0, leaves_remaining=12),
    ),
    dict(
        name="Rohit Bhatia",
        role="Financial Analyst",
        department="Finance",
        email="rohit.bhatia@company.com",
        phone="+91-9876543219",
        image="https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&h=300&fit=crop&crop=faces",
        is_active=True,
        status="Active",
        salary=71000,
        joining_date="2022-06-14",
        location="Pune",
        years_of_experience=4.1,
        performance_rating=3.9,
        grade="B",
        last_appraisal_date="2025-12-14",
        last_increment_percent=6,
        attendance=dict(total_working_days=22, days_present=18, days_absent=4, total_leaves=12, leaves_taken=4, leaves_remaining=8),
    ),
    dict(
        name="Meera Pillai",
        role="Finance Manager",
        department="Finance",
        email="meera.pillai@company.com",
        phone="+91-9876543220",
        image="https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=300&h=300&fit=crop&crop=faces",
        is_active=True,
        status="Active",
        salary=98000,
        joining_date="2019-09-30",
        location="Hyderabad",
        years_of_experience=8.4,
        performance_rating=4.8,
        grade="A+",
        last_appraisal_date="2026-01-30",
        last_increment_percent=11,
        attendance=dict(total_working_days=22, days_present=21, days_absent=1, total_leaves=12, leaves_taken=1, leaves_remaining=11),
    ),
    dict(
        name="Siddharth Rao",
        role="HR Executive",
        department="Human Resources",
        email="siddharth.rao@company.com",
        phone="+91-9876543221",
        image="https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=300&h=300&fit=crop&crop=faces",
        is_active=True,
        status="Active",
        salary=55000,
        joining_date="2023-02-06",
        location="Bangalore",
        years_of_experience=2.3,
        performance_rating=3.6,
        grade="B",
        last_appraisal_date="2025-08-06",
        last_increment_percent=4,
        attendance=dict(total_working_days=22, days_present=17, days_absent=5, total_leaves=12, leaves_taken=5, leaves_remaining=7),
    ),
    dict(
        name="Kavya Nambiar",
        role="HR Manager",
        department="Human Resources",
        email="kavya.nambiar@company.com",
        phone="+91-9876543222",
        image="https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=300&h=300&fit=crop&crop=faces",
        is_active=True,
        status="Active",
        salary=84000,
        joining_date="2021-01-11",
        location="Delhi",
        years_of_experience=6.6,
        performance_rating=4.4,
        grade="A",
        last_appraisal_date="2026-01-11",
        last_increment_percent=8,
        attendance=dict(total_working_days=22, days_present=20, days_absent=2, total_leaves=12, leaves_taken=2, leaves_remaining=10),
    ),
    dict(
        name="Nikhil Chawla",
        role="DevOps Engineer",
        department="Engineering",
        email="nikhil.chawla@company.com",
        phone="+91-9876543223",
        image="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&h=300&fit=crop&crop=faces",
        is_active=True,
        status="Active",
        salary=88000,
        joining_date="2021-10-25",
        location="Chennai",
        years_of_experience=5.5,
        performance_rating=4.5,
        grade="A",
        last_appraisal_date="2026-02-25",
        last_increment_percent=9,
        attendance=dict(total_working_days=22, days_present=22, days_absent=0, total_leaves=12, leaves_taken=0, leaves_remaining=12),
    ),
    dict(
        name="Ishita Sen",
        role="Data Analyst",
        department="Engineering",
        email="ishita.sen@company.com",
        phone="+91-9876543224",
        image="https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?w=300&h=300&fit=crop&crop=faces",
        is_active=True,
        status="Active",
        salary=69000,
        joining_date="2022-12-19",
        location="Mumbai",
        years_of_experience=3.0,
        performance_rating=4.1,
        grade="B",
        last_appraisal_date="2025-12-19",
        last_increment_percent=5,
        attendance=dict(total_working_days=22, days_present=19, days_absent=3, total_leaves=12, leaves_taken=3, leaves_remaining=9),
    ),
    dict(
        name="Aman Gupta",
        role="Product Manager",
        department="Product",
        email="aman.gupta@company.com",
        phone="+91-9876543225",
        image="https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&h=300&fit=crop&crop=faces",
        is_active=True,
        status="Active",
        salary=93000,
        joining_date="2020-05-18",
        location="Pune",
        years_of_experience=6.9,
        performance_rating=4.7,
        grade="A+",
        last_appraisal_date="2026-01-18",
        last_increment_percent=10,
        attendance=dict(total_working_days=22, days_present=21, days_absent=1, total_leaves=12, leaves_taken=1, leaves_remaining=11),
    ),
    dict(
        name="Pooja Desai",
        role="Product Analyst",
        department="Product",
        email="pooja.desai@company.com",
        phone="+91-9876543226",
        image="https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?w=300&h=300&fit=crop&crop=faces",
        is_active=False,
        status="On Leave",
        salary=64000,
        joining_date="2023-03-27",
        location="Hyderabad",
        years_of_experience=2.6,
        performance_rating=3.7,
        grade="B",
        last_appraisal_date="2025-09-27",
        last_increment_percent=4,
        attendance=dict(total_working_days=22, days_present=13, days_absent=9, total_leaves=12, leaves_taken=9, leaves_remaining=3),
    ),
    dict(
        name="Varun Khanna",
        role="Legal Counsel",
        department="Legal",
        email="varun.khanna@company.com",
        phone="+91-9876543227",
        image="https://images.unsplash.com/photo-1552058544-f2b08422138a?w=300&h=300&fit=crop&crop=faces",
        is_active=True,
        status="Active",
        salary=97000,
        joining_date="2019-11-04",
        location="Delhi",
        years_of_experience=9.2,
        performance_rating=4.6,
        grade="A+",
        last_appraisal_date="2026-01-04",
        last_increment_percent=8,
        attendance=dict(total_working_days=22, days_present=20, days_absent=2, total_leaves=12, leaves_taken=2, leaves_remaining=10),
    ),
    dict(
        name="Neha Joshi",
        role="Compliance Officer",
        department="Legal",
        email="neha.joshi@company.com",
        phone="+91-9876543228",
        image="https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=300&h=300&fit=crop&crop=faces",
        is_active=True,
        status="Active",
        salary=76000,
        joining_date="2022-02-14",
        location="Bangalore",
        years_of_experience=4.4,
        performance_rating=4.0,
        grade="B",
        last_appraisal_date="2025-08-14",
        last_increment_percent=6,
        attendance=dict(total_working_days=22, days_present=18, days_absent=4, total_leaves=12, leaves_taken=4, leaves_remaining=8),
    ),
    dict(
        name="Suresh Pillai",
        role="Customer Support Lead",
        department="Support",
        email="suresh.pillai@company.com",
        phone="+91-9876543229",
        image="https://images.unsplash.com/photo-1560250097-b93528c311a5?w=300&h=300&fit=crop&crop=faces",
        is_active=True,
        status="Active",
        salary=61000,
        joining_date="2021-08-09",
        location="Chennai",
        years_of_experience=5.0,
        performance_rating=4.2,
        grade="A",
        last_appraisal_date="2026-02-09",
        last_increment_percent=7,
        attendance=dict(total_working_days=22, days_present=21, days_absent=1, total_leaves=12, leaves_taken=1, leaves_remaining=11),
    ),
    dict(
        name="Riya Kulkarni",
        role="Support Associate",
        department="Support",
        email="riya.kulkarni@company.com",
        phone="+91-9876543230",
        image="https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=300&h=300&fit=crop&crop=faces",
        is_active=False,
        status="Inactive",
        salary=48000,
        joining_date="2023-07-03",
        location="Mumbai",
        years_of_experience=1.5,
        performance_rating=3.2,
        grade="C",
        last_appraisal_date="2025-07-03",
        last_increment_percent=0,
        attendance=dict(total_working_days=22, days_present=11, days_absent=11, total_leaves=12, leaves_taken=11, leaves_remaining=1),
    ),
    dict(
        name="Manish Trivedi",
        role="IT Administrator",
        department="IT",
        email="manish.trivedi@company.com",
        phone="+91-9876543231",
        image="https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=300&h=300&fit=crop&crop=faces",
        is_active=True,
        status="Active",
        salary=73000,
        joining_date="2022-04-28",
        location="Pune",
        years_of_experience=4.7,
        performance_rating=4.1,
        grade="B",
        last_appraisal_date="2025-10-28",
        last_increment_percent=6,
        attendance=dict(total_working_days=22, days_present=19, days_absent=3, total_leaves=12, leaves_taken=3, leaves_remaining=9),
    ),
]


class Command(BaseCommand):
    help = "Seeds the database with the sample employees used by the React frontend."

    def handle(self, *args, **options):
        created_count = 0
        for data in EMPLOYEES:
            attendance_data = data.pop("attendance")
            employee, created = Employee.objects.update_or_create(
                email=data["email"], defaults=data
            )
            Attendance.objects.update_or_create(
                employee=employee, defaults=attendance_data
            )
            if created:
                created_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Seeded {len(EMPLOYEES)} employees ({created_count} newly created)."
            )
        )
